# SwiftLint Configuration for SwiftBoard

# Paths to include/exclude
included:
  - SwiftBoard
  - SwiftBoardTests
  - SwiftBoardUITests

excluded:
  - DerivedData
  - .build
  - Pods
  - SwiftBoard.xcodeproj
  - SwiftBoard.xcworkspace

# Rules to enable/disable
disabled_rules:
  - todo
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - identifier_name
  - trailing_whitespace
  - vertical_whitespace
  - force_cast
  - force_unwrapping
  - implicitly_unwrapped_optional
  - unused_closure_parameter
  - unneeded_parentheses_in_closure_argument
  - attributes
  - sorted_imports
  - file_header
  - extension_access_modifier
  - pattern_matching_keywords
  - number_separator
  - implicit_return
  - prefixed_toplevel_constant
  - static_over_final_class
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces

opt_in_rules:
  - array_init
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - function_default_parameter_at_end
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - unavailable_function
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - xct_specific_matcher
  - yoda_condition

# Custom rules
custom_rules:
  # Prevent force unwrapping in production code
  no_force_unwrapping:
    name: "No Force Unwrapping"
    regex: '!\s*$'
    match_kinds:
      - comment
      - doccomment
      - string
    message: "Force unwrapping should be avoided in production code"
    severity: warning

  # Enforce TCA naming conventions
  tca_action_naming:
    name: "TCA Action Naming"
    regex: 'enum\s+\w+Action'
    match_kinds:
      - typeidentifier
    message: "TCA Action enums should end with 'Action'"
    severity: warning

  tca_state_naming:
    name: "TCA State Naming"
    regex: 'struct\s+\w+State'
    match_kinds:
      - typeidentifier
    message: "TCA State structs should end with 'State'"
    severity: warning

# Configuration for enabled rules only
closure_body_length:
  warning: 30
  error: 50

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3
    error: 6

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 60
